version: "3.8"

volumes:
  mysql_data:
  storage_data:

services:
  sqldb:
    image: mysql:5.7
    container_name: helper-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=helper
      - MYSQL_USER=helper
      - MYSQL_PASSWORD=helper
      - MYSQL_ROOT_PASSWORD=helper
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - helper-network

  helper:
    image: eloufirhatim/helper:latest
    container_name: helper-server
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=sqldb
      - DB_PORT=3306
      - DB_DATABASE=helper
      - DB_USERNAME=helper
      - DB_PASSWORD=helper
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=your_username
      - MAIL_PASSWORD=your_password
      - MAIL_ENCRYPTION=tls
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      sqldb:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - storage_data:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - helper-network

networks:
  helper-network:
    driver: bridge
